#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import with_statement
import sys, socket
import psycopg2, psycopg2.extras
from optparse import OptionParser

def main(argv=None):
    if argv is None:
        argv = sys.argv

    parser = OptionParser()
    #parser.add_option("-r", "--rdns", action="store_true", dest="rdns", help="Get logs with IPs resolved via RDNS", default=False)
    (options, args) = parser.parse_args(argv)

    #if len(args) != 2:
    #   print >> sys.stderr, "Usage: traffic.py <VirtualHost>"
    #   return 1

    DATABASE_PASSWORD = 'z62VUW2m59Y69u99'
    db = psycopg2.connect("host='db1.igowo.de' user='pysk' password='%s' dbname='pysk'" % (DATABASE_PASSWORD,))
    cursor = db.cursor(cursor_factory=psycopg2.extras.DictCursor)

    query = "SELECT DISTINCT host, ip FROM server_ip_list WHERE host(ip) LIKE '10.0.%'"
    cursor.execute(query)

    print("""\
#
# Shorewall version 4 - Rules File (auto-generated by pysk)
#
""")

    processed_hosts = {}
    for row in cursor.fetchall():
        if not row["host"] in processed_hosts:
            print "# %s" % (row["host"],)
            print "DNAT net vz:%s:22 tcp 22%s - 81.95.0.210" % (row["ip"], row["ip"].split(".")[-1],)
            print ""

if __name__ == "__main__":
    sys.exit(main())
