#!/bin/bash

set -e
set -u

DBNAME=$1
DBPASS=$2

psql -U postgres template1 -f - <<EOT
CREATE ROLE $DBNAME NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD '$DBPASS';
CREATE DATABASE $DBNAME WITH OWNER=$DBNAME;
EOT

psql -U postgres $DBNAME -f - <<EOT
GRANT ALL ON SCHEMA public TO $DBNAME WITH GRANT OPTION;
EOT

