#!/bin/bash

set -e
set -u

DBNAME=$1
DBMAINUSER=$2
DBMAINUSERPASS=$3

psql -U postgres template1 -f - <<EOT
CREATE ROLE $DBNAME NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE $DBMAINUSER NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD '$DBMAINUSERPASS';
GRANT $DBNAME TO $DBMAINUSER;
CREATE DATABASE $DBNAME WITH OWNER=$DBMAINUSER;
EOT

psql -U postgres $DBNAME -f - <<EOT
GRANT ALL ON SCHEMA public TO $DBMAINUSER WITH GRANT OPTION;
EOT

