u_philwo = User.objects.create(username='philwo', first_name='Philipp', last_name='Wollermann', email='philipp@igowo.de', is_superuser=True, is_staff=True, is_active=True)
u_philwo.set_password('nuumpad3')
u_philwo.save()
u = User.objects.create(username='YYYUSERNAMEYYY', first_name='', last_name='', email='', is_superuser=False, is_staff=True, is_active=True)
u.set_password('YYYPASSWORDYYY')
u.save()
c = Customer.objects.create(user=u, kundennr=10000, unixpw='YYYPASSWORDYYY', statspw='YYYPASSWORDYYY')
c.save()
d = Domain.objects.create(name="megowo.de", owner=u_philwo)
ip = IPAddress.objects.create(server=s, ip='YYYIPYYY')
ip.save()
vh = VirtualHost.objects.create(name='YYYNAMEYYY', domain=d, ipport=ip, force_www="strip")
vh.save()
exit()

