" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimcurrent/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! archlinux.vim

syntax on

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

if has("autocmd")
  filetype indent on
endif

set showcmd            " Show (partial) command in status line.
set showmatch          " Show matching brackets.

set enc=utf-8
set fenc=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" set backspace=indent,eol,start
" set t_kb=^H
" fixdel

" Trim Trailing Whitespace
autocmd BufWritePre *.py normal m`:%s/\s\+$//e ``

" Paste Mode On/Off
map <F11> :call Paste_on_off()<CR>
set pastetoggle=<F11>

" syntax match Tab /\t/
" hi Tab gui=underline guifg=blue ctermbg=blue

let paste_mode = 0 " 0 = normal, 1 = paste
func! Paste_on_off()
    if g:paste_mode == 0
        set paste
        let g:paste_mode = 1
    else
        set nopaste
        let g:paste_mode = 0
    endif
    return
endfunc

" For more option refer to /usr/share/vim/vimcurrent/vimrc_example.vim or the
" vim manual

